.TH ZIMCHECK "1" "July 2020" "zim-tools" "User Commands"
.SH NAME
zimcheck \- a tool to check the quality of a ZIM file
.SH SYNOPSIS
\fBkiwix\-compile\-resources\fR [options] zimfile\fR
.SH DESCRIPTION
.TP
zimfile
The ZIM file to check
.TP
\fB\-A\fR, \fB\-\-all\fR
run all tests. Default if no flags are given
.TP
\fB\-0\fR, \fB\-\-empty\fR
Empty content
.TP
\fB\-C\fR, \fB\-\-checksum\fR
Internal CheckSum Test
.TP
\fB\-M\fR, \fB\-\-metadata\fR
MetaData entries
.TP
\fB\-F\fR, \fB\-\-favicon\fR
Favicon
.TP
\fB\-P\fR, \fB\-\-main\fR
Main page
.TP
\fB\-R\fR, \fB\-\-redundant\fR
Redundant data check
.TP
\fB\-U\fR, \fB\-\-url_internal\fR
URL check \- Internal URLs
.TP
\fB\-X\fR, \fB\-\-url_external\fR
URL check \- External URLs
.TP
\fB\-E\fR, \fB\-\-mime\fR
MIME checks
.TP
\fB\-D\fR, \fB\-\-details\fR
Details of error
.TP
\fB\-B\fR, \fB\-\-progress\fR
Print progress report
.TP
\fB\-H\fR, \fB\-\-help\fR
Displays Help
.TP
\fB\-V\fR, \fB\-\-version\fR
Displays software version
.SH AUTHOR
Kiran Mathew Koshy

