.TH ZIMDIFF "1" "July 2020" "zim-tools" "User Commands"
.SH NAME
zimdiff \- A tool to obtain the diff_file between two ZIM files in order to facilitate incremental updates
.SH SYNOPSIS
\fBzimdiff\fR [options] start_file end_file output_file\fR
.SH DESCRIPTION
.TP
start_file
ZIM file to start from
.TP
end_file
ZIM file to diff against
.TP
output_file
File to write diff to
.TP
\fB\-v\fR, \fB\-\-version\fR
print software version
.TP
\fB\-h\fR, \fB\-\-help\fR
print help

