.TH ZIMPATCH "1" "July 2020" "zim-tools" "User Commands"
.SH NAME
zimpatch \- tool to compute the end_file using a start_file and a diff_file
.SH SYNOPSIS
\fBzimpatch\fR [options] start_file diff_file output_file\fR
.SH DESCRIPTION
.TP
start_file
Start/original file
.TP
diff_file
Diff/patch file to apply
.TP
output_file
File to output to
.TP
\fB\-h\fR, \fB\-\-help\fR
show a help message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
print software version

