.TH ZIMRECREATE "1" "July 2020" "zim-tools" "User Commands"
.SH NAME
zimrecreate \- tool to recreate a ZIM files from a existing ZIM
.SH SYNOPSIS
\fBzimpatch\fR [options] origin_file output_file\fR
.SH DESCRIPTION
.TP
origin_file
Original file
.TP
output_file
File to output to
.TP
\fB\-h\fR, \fB\-\-help\fR
show a help message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
print software version

