.TH ZIMSEARCH "1" "July 2020" "zim-tools" "User Commands"
.SH NAME
zimsearch \- search a ZIM file
.SH SYNOPSIS
\fBzimsearch\fR [\-x INDEXFILE] zimfile searchstring\fR
.SH DESCRIPTION
.TP
zimfile
ZIM file to search
.TP
searchstring
Query to search
.TP
\fB\-x\fR INDEXFILE
Specify indexfile
.TP
\fB\-v\fR, \fB\-\-version\fR
print software version

