language: cpp
dist: xenial
sudo: true
cache: ccache
before_install:
- PATH=$PATH:$HOME/bin
install: travis/install_deps.sh
script: travis/compile.sh
env:
  matrix:
    - PLATFORM="native_static"
    - PLATFORM="native_dyn"
addons:
  apt:
    packages:
      - python3.5
      - python3-pip
      - libbz2-dev
      - ccache
      - zlib1g-dev
      - uuid-dev
matrix:
  include:
    - env: PLATFORM="native_dyn"
      os: osx
